-- MySQL Script generated by MySQL Workbench
-- Tue Aug 11 11:17:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CineCat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CineCat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CineCat` DEFAULT CHARACTER SET utf8 ;
USE `CineCat` ;

-- -----------------------------------------------------
-- Table `CineCat`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`filme` (
  `id_filme` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `duracao` INT NULL,
  `classificacao` VARCHAR(45) NULL,
  `sinopse` TEXT NULL,
  PRIMARY KEY (`id_filme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`sala` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `capacidade` INT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`sessao` (
  `id_sessao` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `horario` TIME NULL,
  `preco` DECIMAL(4,2) NULL,
  `id_filme` INT NOT NULL,
  `id_sala` INT NOT NULL,
  PRIMARY KEY (`id_sessao`),
  INDEX `fk_sessao_filme_idx` (`id_filme` ASC) VISIBLE,
  INDEX `fk_sessao_sala1_idx` (`id_sala` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `CineCat`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessao_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `CineCat`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`assento` (
  `idassento` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `fila` VARCHAR(45) NULL,
  PRIMARY KEY (`idassento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`ingresso` (
  `id_ingresso` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_sessao` INT NOT NULL,
  `assento_idassento` INT NOT NULL,
  `formapagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ingresso`),
  INDEX `fk_ingresso_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_ingresso_sessao1_idx` (`id_sessao` ASC) VISIBLE,
  INDEX `fk_ingresso_assento1_idx` (`assento_idassento` ASC) VISIBLE,
  CONSTRAINT `fk_ingresso_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `CineCat`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresso_sessao1`
    FOREIGN KEY (`id_sessao`)
    REFERENCES `CineCat`.`sessao` (`id_sessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresso_assento1`
    FOREIGN KEY (`assento_idassento`)
    REFERENCES `CineCat`.`assento` (`idassento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CineCat`.`sala_has_assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CineCat`.`sala_has_assento` (
  `sala_id_sala` INT NOT NULL,
  `assento_idassento` INT NOT NULL,
  PRIMARY KEY (`sala_id_sala`, `assento_idassento`),
  INDEX `fk_sala_has_assento_assento1_idx` (`assento_idassento` ASC) VISIBLE,
  INDEX `fk_sala_has_assento_sala1_idx` (`sala_id_sala` ASC) VISIBLE,
  CONSTRAINT `fk_sala_has_assento_sala1`
    FOREIGN KEY (`sala_id_sala`)
    REFERENCES `CineCat`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_has_assento_assento1`
    FOREIGN KEY (`assento_idassento`)
    REFERENCES `CineCat`.`assento` (`idassento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
